import type { Metadata } from "next";
import Header from "@/app/_component/Header";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const themeInitializerScript = `
  (function () {
    let theme = window.localStorage.getItem("theme");
    theme = theme == 'light'?  'light' :  "dark";
    document.documentElement.classList = theme;
    window.localStorage.setItem("theme",theme)
  })();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <script dangerouslySetInnerHTML={{ __html: themeInitializerScript }} />
        {/* <Header /> */}
        {children}
      </body>
    </html>
  );
}
