import type { Metadata } from "next";
import Header from "@/app/_component/Header";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const themeInitializerScript = `
  (function () {
    window.localStorage.getItem("theme") == 'light'? document.documentElement.classList = 'light' : document.body.classList = "dark"
  })();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <script dangerouslySetInnerHTML={{ __html: themeInitializerScript }} />
        <Header />
        {children}
      </body>
    </html>
  );
}
